definitions:
  account.Account:
    properties:
      Account_ID:
        type: integer
      DocumentNumber:
        type: string
    type: object
  account.Transaction:
    properties:
      AccountID:
        type: integer
      Amount:
        type: number
      EventDate:
        type: string
      OperationsTypeID:
        type: integer
      TransactionID:
        type: integer
    type: object
info:
  contact: {}
paths:
  /v1/account:
    post:
      description: NewAccounts endpoint save a new account
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/account.Account'
      summary: Get NewAccounts
  /v1/accounts/:accountID:
    get:
      description: GetAccounts endpoint get account
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/account.Account'
      summary: Get GetAccounts
  /v1/operationtypes:
    get:
      description: GetOperationsTypes endpoint get all operations type
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: array
      summary: Get GetOperationsTypes
  /v1/transaction:
    post:
      description: NewTransaction endpoint save a new transaction
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/account.Transaction'
      summary: Post NewTransaction
swagger: "2.0"
