version: '3.7'

services:
    mysqltest:
        image: mysql
        restart: always
        environment:
            MYSQL_TCP_PORT: 3309
            MYSQL_DATABASE: 'db'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'password'
            MYSQL_ROOT_PASSWORD: 'password'
        ports:
            - '3309:3309'
        networks:
            - test-network
        expose:
            - '3309'
    test:
        image: golang:1.15
        environment:
        - API_DB_DATABASE=mysql
        - API_DB_CONNECTION=user:password@tcp(mysqltest:3309)/db
        networks:
            - test-network
        volumes:
            - $PWD:/go/src/account-test
        working_dir: /go/src/account-test
        depends_on:
            - mysqltest
        command: bash -c "go test -v -cover $$(go list ./... | grep -v /vendor/)"
networks:
    test-network: