version: '3.7'

services:
    mysql:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_DATABASE: 'db'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'password'
            MYSQL_ROOT_PASSWORD: 'password'
        ports:
            - '3306:3306'
        networks:
            - dev-network
        expose:
            - '3306'
        volumes:
            - my-db:/var/lib/mysql
    app:
        image: golang:1.15
        environment:
            - API_SERVICE_NAME=transaction
            - API_SERVER_ADDRESS=:8080
            - API_SERVER_MODE=debug
            - API_DB_DATABASE=mysql
            - API_DB_DATAMIGRATION=true
            - API_DB_CONNECTION=user:password@tcp(mysql:3306)/db
        ports:
            - 8080:8080
        networks:
            - dev-network
        volumes:
            - $PWD:/go/src/app
        working_dir: /go/src/app
        depends_on:
            - mysql
        command: bash -c "CGO_ENABLED=0 GOOS=linux go build -mod vendor -a -o ./app ./cmd/app && ./app"
volumes:
    my-db:

networks:
    dev-network: