version: '3.7'

services:
    mysql:
        image: mysql
        restart: always
        environment:
            MYSQL_TCP_PORT: 3308
            MYSQL_DATABASE: 'db'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'password'
            MYSQL_ROOT_PASSWORD: 'password'
        ports:
            - '3308:3308'
        networks:
            - dev-network
        expose:
            - '3308'
    app:
        image: golang:1.15
        ports:
            - 8080:8080
        networks:
            - dev-network
        env_file:
          - env.list
        volumes:
            - $PWD:/go/src/app
        working_dir: /go/src/app
        depends_on:
            - mysql
        command: bash -c "CGO_ENABLED=0 GOOS=linux go build -mod vendor -a -o ./app ./cmd/app && ./app"
networks:
    dev-network: