version: '3.7'

services:
    mysqltest:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_DATABASE: 'db'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'password'
            MYSQL_ROOT_PASSWORD: 'password'
        ports:
            - '3309:3306'
        networks:
            - test-network
        expose:
            - '3309'
        volumes:
            - my-db:/var/lib/mysql
    test:
        image: golang:1.15
        environment:
        - API_DB_DATABASE=mysql
        - API_DB_CONNECTION=user:password@tcp(mysqltest:3309)/db
        - API_DB_DATAMIGRATION=false
        networks:
            - test-network
        volumes:
            - $PWD:/go/src/account-test
        working_dir: /go/src/account-test
        depends_on:
            - mysqltest
        command: bash -c "go test -count=10 -race -cover ./..."
volumes:
    my-db:

networks:
    test-network: