// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package api

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/account": {
            "post": {
                "description": "NewAccounts endpoint save a new account",
                "produces": [
                    "application/json"
                ],
                "summary": "Get NewAccounts",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/account.Account"
                        }
                    }
                }
            }
        },
        "/v1/accounts/:accountID": {
            "get": {
                "description": "GetAccounts endpoint get account",
                "produces": [
                    "application/json"
                ],
                "summary": "Get GetAccounts",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/account.Account"
                        }
                    }
                }
            }
        },
        "/v1/operationtypes": {
            "get": {
                "description": "GetOperationsTypes endpoint get all operations type",
                "produces": [
                    "application/json"
                ],
                "summary": "Get GetOperationsTypes",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array"
                        }
                    }
                }
            }
        },
        "/v1/transaction": {
            "post": {
                "description": "NewTransaction endpoint save a new transaction",
                "produces": [
                    "application/json"
                ],
                "summary": "Post NewTransaction",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/account.Transaction"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "account.Account": {
            "type": "object",
            "properties": {
                "Account_ID": {
                    "type": "integer"
                },
                "DocumentNumber": {
                    "type": "string"
                }
            }
        },
        "account.Transaction": {
            "type": "object",
            "properties": {
                "AccountID": {
                    "type": "integer"
                },
                "Amount": {
                    "type": "number"
                },
                "EventDate": {
                    "type": "string"
                },
                "OperationsTypeID": {
                    "type": "integer"
                },
                "TransactionID": {
                    "type": "integer"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
